spring:
  datasource:
    name: htyback  #????
    url: jdbc:mysql://http://103.140.126.173/:3306/htyback #url
    username: htyback  #???
    password: 3Dx2RDrJpJaEPXyA  #??
    driver-class-name: com.mysql.jdbc.Driver  #???????
#server:
#  port: 8080

#mybatis:
#  mapper-locations: classpath:mapper/*.xml  #??????
#  type-aliases-package: com.xzy.springtest.bean #?????
#
#spring.profiles.active: local
